<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit62b13acd316800fd736c31b78b056917
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Curl\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Curl\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-curl-class/php-curl-class/src/Curl',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'RetailCrm\\' => 
            array (
                0 => __DIR__ . '/..' . '/retailcrm/api-client-php/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit62b13acd316800fd736c31b78b056917::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit62b13acd316800fd736c31b78b056917::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit62b13acd316800fd736c31b78b056917::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
